language: python
python:
  - "3.3"
  - "3.4"
install:
  - pip install --use-wheel --use-mirrors -r build-requirements.txt
  - pip install --use-wheel --use-mirrors coveralls
script:
  - coverage run --source=py1 setup.py test
  # Checks that pip can install the package.
  - pip install .
after_success:
  - coveralls
