language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
install:
  - pip install -r build-requirements.txt
  - pip install coveralls
script:
  - coverage run --source=py1 setup.py test
  # Checks that pip can install the package.
  - pip install .
after_success:
  - coveralls
